// Generated by gencpp from file pathing/waypoints.msg
// DO NOT EDIT!


#ifndef PATHING_MESSAGE_WAYPOINTS_H
#define PATHING_MESSAGE_WAYPOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pathing
{
template <class ContainerAllocator>
struct waypoints_
{
  typedef waypoints_<ContainerAllocator> Type;

  waypoints_()
    : xs()
    , ys()  {
    }
  waypoints_(const ContainerAllocator& _alloc)
    : xs(_alloc)
    , ys(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _xs_type;
  _xs_type xs;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _ys_type;
  _ys_type ys;





  typedef boost::shared_ptr< ::pathing::waypoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pathing::waypoints_<ContainerAllocator> const> ConstPtr;

}; // struct waypoints_

typedef ::pathing::waypoints_<std::allocator<void> > waypoints;

typedef boost::shared_ptr< ::pathing::waypoints > waypointsPtr;
typedef boost::shared_ptr< ::pathing::waypoints const> waypointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pathing::waypoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pathing::waypoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pathing::waypoints_<ContainerAllocator1> & lhs, const ::pathing::waypoints_<ContainerAllocator2> & rhs)
{
  return lhs.xs == rhs.xs &&
    lhs.ys == rhs.ys;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pathing::waypoints_<ContainerAllocator1> & lhs, const ::pathing::waypoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pathing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pathing::waypoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pathing::waypoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pathing::waypoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pathing::waypoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pathing::waypoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pathing::waypoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pathing::waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86ce9604e58ca9c772c5cdb0f6a5a8ac";
  }

  static const char* value(const ::pathing::waypoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86ce9604e58ca9c7ULL;
  static const uint64_t static_value2 = 0x72c5cdb0f6a5a8acULL;
};

template<class ContainerAllocator>
struct DataType< ::pathing::waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pathing/waypoints";
  }

  static const char* value(const ::pathing::waypoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pathing::waypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] xs\n"
"float64[] ys\n"
;
  }

  static const char* value(const ::pathing::waypoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pathing::waypoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xs);
      stream.next(m.ys);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct waypoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pathing::waypoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pathing::waypoints_<ContainerAllocator>& v)
  {
    s << indent << "xs[]" << std::endl;
    for (size_t i = 0; i < v.xs.size(); ++i)
    {
      s << indent << "  xs[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.xs[i]);
    }
    s << indent << "ys[]" << std::endl;
    for (size_t i = 0; i < v.ys.size(); ++i)
    {
      s << indent << "  ys[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.ys[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATHING_MESSAGE_WAYPOINTS_H
