############################################################ SEARCHING ALGORITHM PARAMS ############################################################

search_goal_update_time: 7 # seconds
search_detail: 90 # % of free mapped cells that need to be seen before the area is considered searched
frontier_detail: 20 # maximum number of frontier cells that can be present before the environment is considered unmapped
local_search_radius: 10 # meters

# costmap weights
unsearched_area_cm_weight: 10
frontier_cm_weight: 10
use_time_cm: false
use_ease_cm: true

# costmap attentiveness (%)
attentiveness: 12

# object detection params
object_width: 0.5 # meters
object_length: 0.5 # meters
pixy_dist_coef: 5551
pixy_dist_exp: -0.459
pixy_angle_coef: 0.2573
stopping_distance: 30 #centimeters

# frontier costmap params
min_frontier_length: 1 # meters # length of the square vicinity around a cell to check for frontier criteria
min_frontier_ratio: 0.2

# obstacle costmap params
obstacle_buffer: 1.5 # meters

# time costmap params
time_threshold: 20 # seconds after a point is seen that the car will start weighting that point at a rate of...
time_priority_slope: 1 # weights per second (max 100)

# unsearched area costmap params
ua_kernel_size: 3 # meters

# ease costmap params
min_ease_dist: 1
max_ease_dist: 10
ease_berth: 120 # degrees
ease_ideal_berth: 80 # degrees
max_ease_ideal_dist: 8
ease_non_ideal_attenuator: 3
ease_weight_ratio_at_berth_limit: 0.5

# view costmap params
pixy_berth: 1.39626 # radians
pixy_range: 4 # meters

############################################################ OTHER ALGORITHM PARAMS ############################################################
# roomba
roomba_reset_time: 4 # seconds
roomba_bufer: 1.5 # meters # distance from wall inside which the car will not try to navigate to

# log and recall
logging_rate: 3 # seconds between logged points
recalling_rate: 6 # seconds before next logged point is set as navigation goal
distance_between_waypoints: 3
pursuing_accuracy: 0.5

# explore
explore_reset_goal_time: 5 # seconds

# wall follow (patrol)
buffer: 1 # meters # target distance from wall

# gap follow (advance)

# puppy guard
guarding_steering_angle: 0.3
guarding_speed: 4 # meters/second

# navigation
uturn_speed: -0.5 # meters/second
idle_speed: 0.38 # meters/second
linger_time: 0.5 # seconds
fix_toggle_time: 1.25 # seconds
back_safety_berth: 90 # degrees
back_safety_margin: 0.6 # meters
front_safety_berth: 90 # degrees
front_safety_margin: 0.3 # meters

############################################################ CAR PARAMS ############################################################

wheelbase: 0.3302 # meters
width: 0.2032 # meters
buffer_length: 5 # steering delay
max_speed: 7. #  meters/second
max_steering_angle: 0.35 # radians
max_accel: 7.51 # meters/second^2
max_decel: 8.26 # meters/second^2
max_steering_vel: 3.2 # radians/second
friction_coeff: 0.523 # - (complete estimate)
height_cg: 0.074 # m (roughly measured to be 3.25 in)
l_cg2rear: 0.17145 # m (decently measured to be 6.75 in)
l_cg2front: 0.15875 # m (decently measured to be 6.25 in)
C_S_front: 4.718 #.79 # 1/rad ? (estimated weight/4)
C_S_rear: 5.4562 #.79 # 1/rad ? (estimated weight/4)
mass: 3.47 # kg (measured on car 'lidart')
moment_inertia: .04712 # kg m^2 (estimated as a rectangle with width and height of car and evenly distributed mass, then shifted to account for center of mass location)

############################################################ LIDAR PARAMS ############################################################
update_lidar_rate: 0.001
scan_beams: 1080
scan_field_of_view: 6.2831853 # 4.71 # radians
scan_distance_to_base_link: 0.275 # meters
scan_std_dev: 0.01 # meters # The standard deviation of the noise applied to the lidar simulation
map_free_threshold: 0.8 # The probability threshold for points in the occupancy grid to be considered "free" in the lidar simulator
ttc_threshold: 0.01 # Time to collision cutoff value in the simulator

############################################################ PATHING PARAMS ############################################################

# Indices for mux controller
mux_size: 5
key_mux_idx: 0
web_mux_idx: 1
wall_follower_mux_idx: 2
gap_follower_mux_idx: 3
navigator_mux_idx: 4

# indices for nav mux controller
nav_mux_size: 6
wanderer_nav_mux_idx: 0
returner_nav_mux_idx: 1
navigator_nav_mux_idx: 2
recaller_nav_mux_idx: 3
explorer_nav_mux_idx: 4
searcher_nav_mux_idx: 5

# keyboard characters for toggling mux
keyboard_key_char: "k"
web_key_char: "o"
brake_key_char: " "
wall_follow_key_char: "p"
gap_follow_key_char: "g"
log_key_char: "l"
random_walk_key_char: "x"
navigate_key_char: "n"
recall_key_char: "r"
return_key_char: "h"
explore_key_char: "e"
search_key_char: "f"
map_clear_key_char: "m"

# web interface strings for toggling mux
keyboard_web_char: "keyboard"
web_web_char: "web"
brake_web_char: "brake"
random_walk_web_char: "wander"
wall_follow_web_char: "patrol"
gap_follow_web_char: "advance"
log_web_char: "log"
return_web_char: "return"
recall_web_char: "recall"
explore_web_char: "explore"
search_web_char: "search"

# simulating parameters
obstacle_size: 2
broadcast_transform: true
publish_ground_truth_pose: true
collision_file: "collision_file" # name of file to write collision log to 

############################################################ TOPIC NAMES ############################################################

# simulating 
distance_transform_topic: "/dt"
pose_topic: "/pose"
ground_truth_pose_topic: "/gt_pose"

# sensing
keyboard_topic: "/key"
web_topic: "/web"
map_topic: "/map"
scan_topic: "/backwards_scan"
odom_topic: "/odom"
pose_rviz_topic: "/initialpose"

# driving
mux_topic: "/pathing/mux"
drive_topic: "/vesc/low_level/ackermann_cmd_mux/input/drive"
wall_follow_drive_topic: "/wall_follow_drive"
gap_follow_drive_topic: "/gap_follow_drive"
navigate_drive_topic: "/pathing/navigate_drive"

# navigating
nav_mux_topic: "/pathing/nav_mux"
random_walker_nav_topic: "/roomba_goal"
navigate_nav_topic: "/navigate_goal"
return_nav_topic: "/return_goal"
waypoints_topic: "/logged_points"
recall_nav_topic: "/recall_goal"
explore_nav_topic: "/explore_goal"
search_nav_topic: "/search_goal"
nav_goal_topic: "/pathing/move_base_simple/goal"

# costmaps
sum_costmap_topic: "/algorithms/navigation/search/sum_costmap"
ease_costmap_topic: "/algorithms/navigation/search/ease_costmap"
frontier_costmap_topic: "/algorithms/navigation/search/frontier_costmap"
obstacle_costmap_topic: "/algorithms/navigation/search/obstacle_costmap"
time_costmap_topic: "/algorithms/navigation/search/time_costmap"
unsearched_area_costmap_topic: "/algorithms/navigation/search/unsearched_area_costmap"
view_costmap_topic: "/algorithms/navigation/search/view_costmap"
seen_points_topic: "/algorithms/navigation/search/seen_points"
global_costmap_topic: "/pathing/move_base/global_costmap/costmap"

# indicating
r0_controller_topic: "/controllers/gpio_inputs/eleven"
r1_controller_topic: "/controllers/gpio_inputs/twelve"

r0_logging_topic: "/controllers/gpio_inputs/thirteen"

r0_pathing_topic: "/controllers/gpio_inputs/twentyone"
r1_pathing_topic: "/controllers/gpio_intputs/twentytwo"
r2_pathing_topic: "/controllers/gpio_inputs/twentythree"
r3_pathing_topic: "/controllers/gpio_intputs/twentyfour"

w0_controller_topic: "/controllers/gpio_outputs/eleven"
w1_controller_topic: "/controllers/gpio_outputs/twelve"

w0_logging_topic: "/controllers/gpio_outputs/thirteen"

w0_pathing_topic: "/controllers/gpio_outputs/twentyone"
w1_pathing_topic: "/controllers/gpio_outputs/twentytwo"
w2_pathing_topic: "/controllers/gpio_outputs/twentythree"
w3_pathing_topic: "/controllers/gpio_outputs/twentyfour"

left_signal_topic: "/controllers/gpio_outputs/thirtyfive"
right_signal_topic: "/controllers/gpio_outputs/thirtysix"
brake_lights_topic: "/controllers/gpio_outputs/thirtyseven"
reverse_lights_topic: "/controllers/gpio_outputs/thirtyeight"
headlights_topic: "/controllers/gpio_outputs/forty"

forward_topic: "/controllers/gpio_outputs/thirtyone"
backward_topic: "/controllers/gpio_outputs/thirtytwo"
left_topic: "/controllers/gpio_outputs/thirtythree"
right_topic: "/controllers/gpio_outputs/sixteen"

front_safety_topic: "/led_control/gpio_outputs/eighteen"
back_safety_topic: "/led_control/gpio_outputs/twentysix"

detection_topic: "/led_control/gpio_outputs/five"
# object_found_topic: "/controllers/gpio_outputs/twentysix"

# collision_topic: "/controllers/gpio_outputs/seven"

############################################################ FRAME NAMES ############################################################

map_frame: "map"
base_frame: "base_footprint"
scan_frame: "backwards_laser"
odom_frame: "odom"
